-- Run as ACCOUNTADMIN. Replace <...> placeholders with your own values.

CREATE WAREHOUSE IF NOT EXISTS WIND_TURBINE_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS WIND_TURBINE;
CREATE SCHEMA IF NOT EXISTS WIND_TURBINE.ANALYTICS;

CREATE STORAGE INTEGRATION IF NOT EXISTS WIND_TURBINE_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/wind-turbine-pipeline-snowflake-s3'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<DATA_LAKE_BUCKET>/curated/latest/');
DESC INTEGRATION WIND_TURBINE_S3_INT;

CREATE STAGE IF NOT EXISTS WIND_TURBINE.ANALYTICS.WIND_TURBINE_CURATED_STAGE
  URL = 's3://<DATA_LAKE_BUCKET>/curated/latest/'
  STORAGE_INTEGRATION = WIND_TURBINE_S3_INT;

USE SCHEMA WIND_TURBINE.ANALYTICS;

CREATE TABLE IF NOT EXISTS SILVER_TURBINE_READINGS (
  TURBINE_ID INTEGER, "TIMESTAMP" TIMESTAMP_NTZ,
  WIND_SPEED NUMBER(10,4), WIND_DIRECTION NUMBER(10,4),
  POWER_OUTPUT NUMBER(10,4), INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLD_SUMMARY_STATISTICS (
  TURBINE_ID INTEGER, MIN_POWER_MW NUMBER(10,4), MAX_POWER_MW NUMBER(10,4),
  AVG_POWER_MW NUMBER(14,8), STDDEV_POWER_MW FLOAT, READING_COUNT INTEGER,
  WINDOW_START TIMESTAMP_NTZ, WINDOW_END TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLD_ANOMALIES (
  TURBINE_ID INTEGER, "TIMESTAMP" TIMESTAMP_NTZ,
  WIND_SPEED NUMBER(10,4), WIND_DIRECTION NUMBER(10,4),
  POWER_OUTPUT NUMBER(10,4), INGESTION_TIMESTAMP TIMESTAMP_NTZ,
  MEAN_POWER_MW NUMBER(14,8), STDDEV_POWER_MW FLOAT,
  LOWER_BOUND_MW FLOAT, UPPER_BOUND_MW FLOAT, IS_ANOMALY BOOLEAN,
  WINDOW_START TIMESTAMP_NTZ, WINDOW_END TIMESTAMP_NTZ
);

CREATE ROLE IF NOT EXISTS WIND_TURBINE_LOADER_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE WIND_TURBINE_WH TO ROLE WIND_TURBINE_LOADER_ROLE;
GRANT USAGE ON DATABASE WIND_TURBINE TO ROLE WIND_TURBINE_LOADER_ROLE;
GRANT USAGE ON SCHEMA WIND_TURBINE.ANALYTICS TO ROLE WIND_TURBINE_LOADER_ROLE;
GRANT USAGE ON STAGE WIND_TURBINE.ANALYTICS.WIND_TURBINE_CURATED_STAGE TO ROLE WIND_TURBINE_LOADER_ROLE;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA WIND_TURBINE.ANALYTICS TO ROLE WIND_TURBINE_LOADER_ROLE;

CREATE USER IF NOT EXISTS WIND_TURBINE_LOADER
  TYPE = SERVICE DEFAULT_ROLE = WIND_TURBINE_LOADER_ROLE
  DEFAULT_WAREHOUSE = WIND_TURBINE_WH RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';
GRANT ROLE WIND_TURBINE_LOADER_ROLE TO USER WIND_TURBINE_LOADER;
